<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Clean REST facade / dispatcher over the mod_minilesson aigen web service functions.
 *
 * Moodle's native REST endpoint dispatches every function through a single
 * server.php?wsfunction=... URL, with PHP bracket-array parameter encoding and a
 * wstoken query parameter. That shape is not consumable by standard REST clients
 * such as ChatGPT custom GPT "Actions" or MCP servers (which need distinct
 * path+method operations, JSON bodies and header-based auth). This script presents
 * the aigen functions as clean resource paths so those clients can call them.
 *
 * It is a GENERIC dispatcher: one path per web service function, of the form
 *
 *     POST {this script}/<function>
 *
 * where <function> is a mod_minilesson aigen function name with the
 * "mod_minilesson_" prefix removed (e.g. aigen_list_itemtypes, list_courses).
 * The JSON request body is the function's arguments. The matching machine-readable
 * spec is generated by openapi.php, which uses the same function set and naming.
 *
 * It does NOT re-implement auth or parameter validation:
 *  - it authenticates the token with core's webservice::authenticate_user()
 *    (the same routine the file download/upload scripts use), which sets up the
 *    user session and enforces the service's own access rules;
 *  - it only brokers functions that belong to the aigenservice external service
 *    (so it can never be used to reach arbitrary Moodle functions), and additionally
 *    requires the caller's own token service to include the function;
 *  - it dispatches through external_api::call_external_function(), which validates
 *    the arguments, runs the function's own capability checks and cleans the return.
 *
 * Auth: send the Moodle web service token in an "X-API-Key" header (recommended -
 * Apache strips Authorization by default). "Authorization: Bearer <token>" is also
 * accepted where the web server forwards it, and a ?token= query parameter is
 * supported for testing only.
 *
 * @package    mod_minilesson
 * @copyright  2026 Justin Hunt (poodllsupport@gmail.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('NO_DEBUG_DISPLAY', true);
// Behave as a stateless web service entry point (token auth, no session cookies).
define('WS_SERVER', true);

require(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/webservice/lib.php');

use core_external\external_api;
use mod_minilesson\constants;

/**
 * Send a JSON response and stop.
 *
 * @param int $status HTTP status code
 * @param array $payload Response body
 * @return never
 */
function aigen_rest_respond(int $status, array $payload) {
    header('Content-Type: application/json; charset=utf-8', true, $status);
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    die;
}

/**
 * Extract the wstoken from the request.
 *
 * Accepts, in order: an "X-API-Key" header (recommended - passes cleanly through
 * Apache, which strips Authorization by default), an "Authorization: Bearer"
 * header, and finally a ?token= query parameter (testing fallback only).
 *
 * @return string the token, or '' if none was supplied
 */
function aigen_rest_token(): string {
    if (!empty($_SERVER['HTTP_X_API_KEY'])) {
        return trim($_SERVER['HTTP_X_API_KEY']);
    }
    $header = '';
    if (!empty($_SERVER['HTTP_AUTHORIZATION'])) {
        $header = $_SERVER['HTTP_AUTHORIZATION'];
    } else if (!empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        // Some Apache configurations expose the header only via the REDIRECT_ prefix.
        $header = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
    }
    if ($header !== '' && preg_match('/^\s*Bearer\s+(.+)$/i', $header, $m)) {
        return trim($m[1]);
    }
    // Testing fallback only: a token query parameter (avoid in production - URLs get logged).
    return isset($_GET['token']) ? trim($_GET['token']) : '';
}

// All facade calls are POST with a JSON body of arguments.
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method !== 'POST') {
    aigen_rest_respond(405, ['error' => true, 'message' => 'Use POST with a JSON body of arguments']);
}

// Resolve the function short name from PATH_INFO (preferred) or a ?path= fallback.
$rawpath = '';
if (!empty($_SERVER['PATH_INFO'])) {
    $rawpath = $_SERVER['PATH_INFO'];
} else if (isset($_GET['path'])) {
    $rawpath = $_GET['path'];
}
$segments = array_values(array_filter(explode('/', trim($rawpath, '/')), 'strlen'));
if (count($segments) !== 1) {
    aigen_rest_respond(404, ['error' => true, 'message' => 'Expected a single function path segment, e.g. /aigen_list_itemtypes']);
}
$shortname = clean_param($segments[0], PARAM_ALPHANUMEXT);
$functionname = 'mod_minilesson_' . $shortname;

// The facade only ever brokers functions that belong to the aigenservice external
// service, so a token for some broader service cannot reach arbitrary functions here.
$aigenservice = $DB->get_record('external_services',
    ['shortname' => 'aigenservice', 'component' => constants::M_COMPONENT, 'enabled' => 1]);
if (!$aigenservice) {
    aigen_rest_respond(503, ['error' => true, 'message' => 'The aigen service is not available on this site']);
}
$facadefunctions = $DB->get_fieldset_select(
    'external_services_functions', 'functionname', 'externalserviceid = ?', [$aigenservice->id]);
if (!in_array($functionname, $facadefunctions)) {
    aigen_rest_respond(404, ['error' => true, 'message' => 'Unknown function: ' . $shortname]);
}

// Authenticate the token using core's webservice routine (validates the token, sets
// up the user session, checks the service is enabled / the user is allowed, etc).
$token = aigen_rest_token();
if ($token === '') {
    aigen_rest_respond(401, ['error' => true, 'message' => 'Missing token (send it as the X-API-Key header)']);
}
$webservice = new webservice();
try {
    $authinfo = $webservice->authenticate_user($token);
} catch (Throwable $e) {
    aigen_rest_respond(401, ['error' => true, 'message' => 'Invalid or unauthorised token']);
}

// The caller's own token service must also grant this function.
if (!$DB->record_exists('external_services_functions',
        ['externalserviceid' => $authinfo['service']->id, 'functionname' => $functionname])) {
    aigen_rest_respond(403, ['error' => true, 'message' => 'This token\'s service is not allowed to call ' . $shortname]);
}

// Decode the JSON request body into the function arguments.
$args = [];
$raw = file_get_contents('php://input');
if ($raw !== '' && $raw !== false) {
    $decoded = json_decode($raw, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($decoded)) {
        aigen_rest_respond(400, ['error' => true, 'message' => 'Request body must be a JSON object of arguments']);
    }
    $args = $decoded;
}

// Dispatch through core, which validates params, runs the function's own capability
// checks and cleans the return value.
$response = external_api::call_external_function($functionname, $args);

if (!empty($response['error'])) {
    $message = $response['exception']->message ?? 'Web service error';
    aigen_rest_respond(400, ['error' => true, 'message' => $message]);
}

aigen_rest_respond(200, ['data' => $response['data']]);
