<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Clean REST facade / dispatcher over the mod_minilesson aigen web service functions.
 *
 * Presents the aigen functions as clean resource paths so standard REST clients (ChatGPT
 * custom GPT Actions, MCP proxies) can call them, rather than Moodle's native
 * server.php?wsfunction=... shape. One path per function:
 *
 *     POST {this script}/<function>
 *
 * where <function> is a mod_minilesson aigen function name with the "mod_minilesson_"
 * prefix removed (e.g. aigen_list_itemtypes, list_courses). The JSON request body is the
 * function's arguments. The matching spec is generated by openapi.php.
 *
 * All shared logic (token auth, the aigenservice allow-list, dispatch) lives in
 * \mod_minilesson\local\aigen\facade; this file is just the HTTP/JSON front-end.
 *
 * Auth: send the Moodle web service token in an "X-API-Key" header (recommended - Apache
 * strips Authorization by default unless the server is configured to forward it).
 * "Authorization: Bearer <token>" is also accepted - this is what an OAuth-issued access
 * token arrives as, when the shared local_oauthmcp authorization server plugin is
 * installed - and a ?token= query parameter for testing only.
 *
 * @package    mod_minilesson
 * @copyright  2026 Justin Hunt (poodllsupport@gmail.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('NO_DEBUG_DISPLAY', true);
// Behave as a stateless web service entry point (token auth, no session cookies).
define('WS_SERVER', true);

// phpcs:ignore moodle.Files.RequireLogin.Missing -- Token-authenticated web service endpoint; auth is via the facade.
require(__DIR__ . '/../../config.php');

use mod_minilesson\local\aigen\facade;

/**
 * Send a JSON response and stop.
 *
 * @param int $status HTTP status code
 * @param array $payload Response body
 * @return never
 */
function aigen_rest_respond(int $status, array $payload) {
    header('Content-Type: application/json; charset=utf-8', true, $status);
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    die;
}

/**
 * Send the 401 challenge header. Matches the header mcp.php sends on the same failure,
 * including the same graceful fallback when local_oauthmcp is not installed.
 *
 * @return void
 */
function aigen_rest_send_auth_challenge(): void {
    global $CFG;
    if (class_exists('\local_oauthmcp\api')) {
        header(
            'WWW-Authenticate: Bearer resource_metadata="' . $CFG->wwwroot . '/mod/minilesson/oauth_resource_metadata.php"',
            true,
            401
        );
        return;
    }
    header('WWW-Authenticate: Bearer', true, 401);
}

/**
 * Serve RFC 9728/8414 discovery JSON (and exit) if this GET's PATH_INFO asks for it and
 * local_oauthmcp is installed - same rationale and shared metadata as mcp.php's identical
 * helper.
 *
 * @return void
 */
function aigen_rest_maybe_send_wellknown_discovery(): void {
    global $CFG;
    if (!class_exists('\local_oauthmcp\api')) {
        return;
    }
    $pathinfo = $_SERVER['PATH_INFO'] ?? '';
    if (strpos($pathinfo, 'oauth-protected-resource') !== false) {
        $data = \local_oauthmcp\api::resource_metadata($CFG->wwwroot . '/mod/minilesson/mcp.php');
        if ($data !== null) {
            aigen_rest_respond(200, $data);
        }
    }
    if (strpos($pathinfo, 'oauth-authorization-server') !== false || strpos($pathinfo, 'openid-configuration') !== false) {
        aigen_rest_respond(200, \local_oauthmcp\api::authorization_server_metadata());
    }
}

// All facade calls are POST with a JSON body of arguments.
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method !== 'POST') {
    if ($method === 'GET') {
        aigen_rest_maybe_send_wellknown_discovery();
    }
    aigen_rest_respond(405, ['error' => true, 'message' => 'Use POST with a JSON body of arguments']);
}

// Resolve the function short name from PATH_INFO (preferred) or a ?path= fallback.
$rawpath = '';
if (!empty($_SERVER['PATH_INFO'])) {
    $rawpath = $_SERVER['PATH_INFO'];
} else if (isset($_GET['path'])) {
    $rawpath = $_GET['path'];
}
$segments = array_values(array_filter(explode('/', trim($rawpath, '/')), 'strlen'));
if (count($segments) !== 1) {
    aigen_rest_respond(404, ['error' => true, 'message' => 'Expected a single function path segment, e.g. /aigen_list_itemtypes']);
}
$shortname = clean_param($segments[0], PARAM_ALPHANUMEXT);
$functionname = facade::full_name($shortname);

// The facade only ever brokers aigenservice functions, so a token for some broader service
// cannot reach arbitrary functions here.
$facadefunctions = facade::function_names();
if (empty($facadefunctions)) {
    aigen_rest_respond(503, ['error' => true, 'message' => 'The aigen service is not available on this site']);
}
if (!in_array($functionname, $facadefunctions)) {
    aigen_rest_respond(404, ['error' => true, 'message' => 'Unknown function: ' . $shortname]);
}

// Authenticate the token (validates it, sets up the user session, checks service access).
$token = facade::request_token();
if ($token === '') {
    aigen_rest_send_auth_challenge();
    aigen_rest_respond(401, ['error' => true, 'message' => 'Missing token (send it as the X-API-Key header)']);
}
try {
    $authinfo = facade::authenticate($token);
} catch (Throwable $e) {
    aigen_rest_send_auth_challenge();
    aigen_rest_respond(401, ['error' => true, 'message' => 'Invalid or unauthorised token']);
}

// The caller's own token service must also grant this function.
if (!facade::token_allows($authinfo, $functionname)) {
    aigen_rest_respond(403, ['error' => true, 'message' => 'This token\'s service is not allowed to call ' . $shortname]);
}

// Decode the JSON request body into the function arguments.
$args = [];
$raw = file_get_contents('php://input');
if ($raw !== '' && $raw !== false) {
    $decoded = json_decode($raw, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($decoded)) {
        aigen_rest_respond(400, ['error' => true, 'message' => 'Request body must be a JSON object of arguments']);
    }
    $args = $decoded;
}

// Dispatch through core (validates params, runs capability checks, cleans the return).
$response = facade::call($functionname, $args);

if (!empty($response['error'])) {
    $message = $response['exception']->message ?? 'Web service error';
    aigen_rest_respond(400, ['error' => true, 'message' => $message]);
}

aigen_rest_respond(200, ['data' => $response['data']]);
